/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elephantMangementSystem;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Timasha
 */
public class healthRecord extends javax.swing.JFrame {

    /**
     * Creates new form healthRecord
     */
    public healthRecord() {
        initComponents();
        this.setResizable(false);
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("MMMM-dd");
        String strDate = formatter.format(date);
        day.setText(strDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JLabel();
        health = new javax.swing.JButton();
        vaccine = new javax.swing.JButton();
        todayVac = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        day.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 30)); // NOI18N
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, 40));

        health.setBackground(new java.awt.Color(255, 255, 255));
        health.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        health.setForeground(new java.awt.Color(255, 255, 255));
        health.setText("ADD health details");
        health.setBorder(null);
        health.setContentAreaFilled(false);
        health.setFocusPainted(false);
        health.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        health.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthMouseClicked(evt);
            }
        });
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });
        getContentPane().add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 30));

        vaccine.setBackground(new java.awt.Color(255, 255, 255));
        vaccine.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine.setForeground(new java.awt.Color(255, 255, 255));
        vaccine.setText("ADD vaccine details");
        vaccine.setBorder(null);
        vaccine.setContentAreaFilled(false);
        vaccine.setFocusPainted(false);
        vaccine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccineMouseClicked(evt);
            }
        });
        vaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        todayVac.setBackground(new java.awt.Color(255, 255, 255));
        todayVac.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        todayVac.setForeground(new java.awt.Color(255, 255, 255));
        todayVac.setText("TODAY'S  Vaccines");
        todayVac.setBorder(null);
        todayVac.setContentAreaFilled(false);
        todayVac.setFocusPainted(false);
        todayVac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todayVac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayVacMouseClicked(evt);
            }
        });
        todayVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayVacActionPerformed(evt);
            }
        });
        getContentPane().add(todayVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void healthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthMouseClicked
        addHealthDetails obj = new addHealthDetails();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_healthMouseClicked

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        
    }//GEN-LAST:event_healthActionPerformed

    private void vaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccineMouseClicked
        addVaccineDetails obj = new addVaccineDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_vaccineMouseClicked

    private void vaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineActionPerformed

    private void todayVacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayVacMouseClicked
        try {
            todayVaccines obj = new todayVaccines();
            obj.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(healthRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_todayVacMouseClicked

    private void todayVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new healthRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day;
    private javax.swing.JButton health;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton todayVac;
    private javax.swing.JButton vaccine;
    // End of variables declaration//GEN-END:variables
}
