/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elephantMangementSystem;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Timasha
 */
public class healthRecord extends javax.swing.JFrame {

    /**
     * Creates new form healthRecord
     */
    public healthRecord() {
        initComponents();
        this.setResizable(false);
        //Date date = new Date();
        //SimpleDateFormat formatter = new SimpleDateFormat("MMMM-dd");
        //String strDate = formatter.format(date);
        //day.setText(strDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        health = new javax.swing.JButton();
        vaccine = new javax.swing.JButton();
        todayVac = new javax.swing.JButton();
        todayVac1 = new javax.swing.JButton();
        todayVac2 = new javax.swing.JButton();
        vaccine1 = new javax.swing.JButton();
        vaccine2 = new javax.swing.JButton();
        vaccine3 = new javax.swing.JButton();
        vaccine4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        health.setBackground(new java.awt.Color(255, 255, 255));
        health.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        health.setForeground(new java.awt.Color(255, 255, 255));
        health.setText("ADD health details");
        health.setBorder(null);
        health.setContentAreaFilled(false);
        health.setFocusPainted(false);
        health.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        health.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthMouseClicked(evt);
            }
        });
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });
        getContentPane().add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 30));

        vaccine.setBackground(new java.awt.Color(255, 255, 255));
        vaccine.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine.setForeground(new java.awt.Color(255, 255, 255));
        vaccine.setText("ADD vaccine details");
        vaccine.setBorder(null);
        vaccine.setContentAreaFilled(false);
        vaccine.setFocusPainted(false);
        vaccine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccineMouseClicked(evt);
            }
        });
        vaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        todayVac.setBackground(new java.awt.Color(255, 255, 255));
        todayVac.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        todayVac.setForeground(new java.awt.Color(255, 255, 255));
        todayVac.setText("TODAY'S  Vaccines");
        todayVac.setBorder(null);
        todayVac.setContentAreaFilled(false);
        todayVac.setFocusPainted(false);
        todayVac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todayVac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayVacMouseClicked(evt);
            }
        });
        todayVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayVacActionPerformed(evt);
            }
        });
        getContentPane().add(todayVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        todayVac1.setBackground(new java.awt.Color(255, 255, 255));
        todayVac1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        todayVac1.setForeground(new java.awt.Color(255, 255, 255));
        todayVac1.setText("TODAY'S  Vaccines");
        todayVac1.setBorder(null);
        todayVac1.setContentAreaFilled(false);
        todayVac1.setFocusPainted(false);
        todayVac1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todayVac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayVac1MouseClicked(evt);
            }
        });
        todayVac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayVac1ActionPerformed(evt);
            }
        });
        getContentPane().add(todayVac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        todayVac2.setBackground(new java.awt.Color(255, 255, 255));
        todayVac2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        todayVac2.setForeground(new java.awt.Color(255, 255, 255));
        todayVac2.setText("TODAY'S  Vaccines");
        todayVac2.setBorder(null);
        todayVac2.setContentAreaFilled(false);
        todayVac2.setFocusPainted(false);
        todayVac2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todayVac2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayVac2MouseClicked(evt);
            }
        });
        todayVac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayVac2ActionPerformed(evt);
            }
        });
        getContentPane().add(todayVac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 30));

        vaccine1.setBackground(new java.awt.Color(255, 255, 255));
        vaccine1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine1.setForeground(new java.awt.Color(255, 255, 255));
        vaccine1.setText("ADD vaccine details");
        vaccine1.setBorder(null);
        vaccine1.setContentAreaFilled(false);
        vaccine1.setFocusPainted(false);
        vaccine1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccine1MouseClicked(evt);
            }
        });
        vaccine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccine1ActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        vaccine2.setBackground(new java.awt.Color(255, 255, 255));
        vaccine2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine2.setForeground(new java.awt.Color(255, 255, 255));
        vaccine2.setText("ADD vaccine details");
        vaccine2.setBorder(null);
        vaccine2.setContentAreaFilled(false);
        vaccine2.setFocusPainted(false);
        vaccine2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccine2MouseClicked(evt);
            }
        });
        vaccine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccine2ActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        vaccine3.setBackground(new java.awt.Color(255, 255, 255));
        vaccine3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine3.setForeground(new java.awt.Color(255, 255, 255));
        vaccine3.setText("ADD vaccine details");
        vaccine3.setBorder(null);
        vaccine3.setContentAreaFilled(false);
        vaccine3.setFocusPainted(false);
        vaccine3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccine3MouseClicked(evt);
            }
        });
        vaccine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccine3ActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        vaccine4.setBackground(new java.awt.Color(255, 255, 255));
        vaccine4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 17)); // NOI18N
        vaccine4.setForeground(new java.awt.Color(255, 255, 255));
        vaccine4.setText("ADD vaccine details");
        vaccine4.setBorder(null);
        vaccine4.setContentAreaFilled(false);
        vaccine4.setFocusPainted(false);
        vaccine4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccine4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccine4MouseClicked(evt);
            }
        });
        vaccine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccine4ActionPerformed(evt);
            }
        });
        getContentPane().add(vaccine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void healthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthMouseClicked
        addHealthDetails obj = new addHealthDetails();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_healthMouseClicked

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        
    }//GEN-LAST:event_healthActionPerformed

    private void vaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccineMouseClicked
        addVaccineDetails obj = new addVaccineDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_vaccineMouseClicked

    private void vaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineActionPerformed

    private void todayVacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayVacMouseClicked
        try {
            todayVaccines obj = new todayVaccines();
            obj.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(healthRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_todayVacMouseClicked

    private void todayVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVacActionPerformed

    private void todayVac1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayVac1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVac1MouseClicked

    private void todayVac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayVac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVac1ActionPerformed

    private void todayVac2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayVac2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVac2MouseClicked

    private void todayVac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayVac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todayVac2ActionPerformed

    private void vaccine1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccine1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine1MouseClicked

    private void vaccine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine1ActionPerformed

    private void vaccine2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccine2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine2MouseClicked

    private void vaccine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine2ActionPerformed

    private void vaccine3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccine3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine3MouseClicked

    private void vaccine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine3ActionPerformed

    private void vaccine4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccine4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine4MouseClicked

    private void vaccine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DashBoard obj = new DashBoard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(healthRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new healthRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton health;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton todayVac;
    private javax.swing.JButton todayVac1;
    private javax.swing.JButton todayVac2;
    private javax.swing.JButton vaccine;
    private javax.swing.JButton vaccine1;
    private javax.swing.JButton vaccine2;
    private javax.swing.JButton vaccine3;
    private javax.swing.JButton vaccine4;
    // End of variables declaration//GEN-END:variables
}
